server:
  port: 8081

spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/trening
    username: root
    password: 11111111
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml


key:
  secret_key: 34753778214125442A472D4B614E645267556B58703273357638792F423F4528